name: Interrogate
description: Queries GitHub content
model: openai/gpt-4.1
modelParameters:
  temperature: 0.7
messages:
  - role: system
    content: >
      Query the given GitHub Issues, Comments, and Discussions and provide a concise answer to the given question.
  - role: user
    content: |
      <content>
      {{content}}
      </content>

      <query>
      {{query}}
      </query>
