name: Rollup 'nUp 'nUp Render
description: Render a Vento.js template as a string using the internal client
author: amyryanmanny

inputs:
  # Authentication
  # At least one of these auth strategies (App, PAT, or default) is required.
  github_token:
    description: |
      GITHUB_TOKEN to authenticate with the GitHub API.
      Should be explicitly set to {{ github.token }} if used.
    required: false
  github_pat_token:
    description: GitHub Personal Access Token to authenticate with the GitHub API.
    required: false
  github_app_id:
    description: GitHub App ID to authenticate with the GitHub API.
    required: false
  github_app_installation_id:
    description: GitHub App Installation ID to authenticate with the GitHub API.
    required: false
  github_app_private_key:
    description: GitHub App Private Key to authenticate with the GitHub API.
    required: false

  # AI Inference
  model_endpoint:
    description: |
      The endpoint to use for AI inference.
      Defaults to models.github.ai, with the org-specific path if using a GitHub App.
    required: false
    # default: https://models.github.ai/
  truncate_tokens:
    description: |
      The maximum number of tokens to truncate to when rendering the template.
    required: false
    # default: 15600

  # Template Config
  template:
    description: The path to the Vento.js template file to render.
    required: false # Defaults to default/summary.md.vto
  update_detection:
    description: >
      An ordered list of strategies used to detect an update from issue comments (see docs for syntax).
    required: false
  emoji_override:
    description: >
      If a matching Emoji exists in the latest update, it will override the Project Field status.
    required: false

  # Slack
  slack_token:
    description: Slack App Token to send notifications.
    required: false
  slack_mute:
    description: Mute Slack notifications if set to "true". Good for testing.
    required: false
  slack_enterprise_domain:
    description: Slack enterprise email domain.
    required: false
    default: "github.com"
  slack_fallback_username:
    description: Fallback GitHub username to DM on Slack, if no assignees exist on an issue.
    required: false
  
  # Debug
  debug_graphql_queries:
    description: Enable detailed logging for GraphQL queries if set to "true".
    required: false

outputs:
  md:
    description: >
      The resulting markdown file from the template engine, rendered as a string.

runs:
  using: node20
  main: ../../dist/render/index.js
