name: Rollup 'nUp 'nUp Push
description: >
  Push Markdown to a list of targets (Repo file, Issue, Discussion, etc) using the internal client
author: amyryanmanny

inputs:
  title:
    description: The title of the document.
    required: false
  title_date:
    description: |
      Override the date to be used by strftime in the title.
      Defaults to TODAY, also supports FRIDAY.
    required: false
  body:
    description: The Markdown string to push.
    required: true
  targets:
    description: The targets to push the string to (see docs for syntax).
    required: true

outputs: {}
# TODO: strftime'd title

runs:
  using: node20
  main: ../../dist/push/index.js
