name: 'Weekly Rollup Example'
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render
        id: render
        uses: ./actions/render
        env:
          SYNAPSE_TLDR: synapse_tldr_gpt
          GITHUB_PAT_TOKEN: ${{ secrets.ROLLUP_PAT_TOKEN }}
        with:
          template: './templates/main.md.vto'

      - name: Push
        id: push
        uses: ./actions/push
        env:
          GITHUB_PAT_TOKEN: ${{ secrets.ROLLUP_PAT_TOKEN }}
        with:
          title: '%Y-%m-%d example_report.md'
          body: ${{ steps.render.outputs.md }}
          targets: |
            repo-file: https://github.com/amyryanmanny/rollup-n-up-n-up/tree/test-push/reports
